In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("Tweet_NFT.csv",names=["id","text","datetime","intent"],header=0)

In [3]:
data.head()

id                                               text  \
0  1212762  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   
1  1212763  Need Sick Character art❓#art #artist #Artist...   
2  1212765  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   
3  1212766  @CryptoBatzNFT @DarekBTW The first project in ...   
4  1212767  @sashadysonn The first project in crypto with ...   

                   datetime        intent  
0  2022-08-06T16:56:36.000Z     Community  
1  2022-08-06T16:56:36.000Z      Giveaway  
2  2022-08-06T16:56:35.000Z  Appreciation  
3  2022-08-06T16:56:35.000Z     Community  
4  2022-08-06T16:56:34.000Z     Community

In [4]:
data["text"]

0         @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...
1         Need Sick Character art❓#art #artist #Artist...
2         @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...
3         @CryptoBatzNFT @DarekBTW The first project in ...
4         @sashadysonn The first project in crypto with ...
                                ...                        
127448    @Jason My company Universe is solving this, an...
127449            @BosoTokyo Many will get rekt in this NFT
127450    @leeneedham81 @KibaInuWorld @HODL_OFFICIAL @Ko...
127451               @1kz3ro @UNLEASHED_NFT I love this job
127452    @Shill_Ronin @UNLEASHED_NFT my proof https://t...
Name: text, Length: 127453, dtype: object

In [5]:
data.shape

(127453, 4)

In [6]:
data.isnull().sum()

id              0
text            0
datetime        0
intent      31089
dtype: int64

In [7]:
data["intent"].value_counts()

Community         41510
Giveaway          21041
Appreciation      16451
Whitelist          8320
Presale            5107
Done               3049
pinksale            477
Interested          276
Launching Soon      133
Name: intent, dtype: int64

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127453 entries, 0 to 127452
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype 
---  ------    --------------   ----- 
 0   id        127453 non-null  int64 
 1   text      127453 non-null  object
 2   datetime  127453 non-null  object
 3   intent    96364 non-null   object
dtypes: int64(1), object(3)
memory usage: 3.9+ MB


In [9]:
data.intent=pd.Categorical(data.intent)
data["intent"]=data.intent.cat.codes

In [10]:
data

id                                               text  \
0       1212762  @crypto_brody @eCoLoGy1990 @MoonrunnersNFT @It...   
1       1212763  Need Sick Character art❓#art #artist #Artist...   
2       1212765  @The_Hulk_NFT @INagotchiNFT @Tesla @killabears...   
3       1212766  @CryptoBatzNFT @DarekBTW The first project in ...   
4       1212767  @sashadysonn The first project in crypto with ...   
...         ...                                                ...   
127448  1278721  @Jason My company Universe is solving this, an...   
127449  1278723          @BosoTokyo Many will get rekt in this NFT   
127450  1278724  @leeneedham81 @KibaInuWorld @HODL_OFFICIAL @Ko...   
127451  1278725             @1kz3ro @UNLEASHED_NFT I love this job   
127452  1278729  @Shill_Ronin @UNLEASHED_NFT my proof https://t...   

                        datetime  intent  
0       2022-08-06T16:56:36.000Z       1  
1       2022-08-06T16:56:36.000Z       3  
2       2022-08-06T16:56:35.000Z       0  
3       2022-08-06T16:56:35.000Z       1  
4       2022-08-06T16:56:34.000Z       1  
...                          ...     ...  
127448  2022-08-08T03:32:01.000Z      -1  
127449  2022-08-08T03:32:00.000Z      -1  
127450  2022-08-08T03:32:00.000Z      -1  
127451  2022-08-08T03:31:59.000Z      -1  
127452  2022-08-08T03:31:58.000Z      -1  

[127453 rows x 4 columns]

In [11]:
data["intent"].value_counts()

 1    41510
-1    31089
 3    21041
 0    16451
 7     8320
 6     5107
 2     3049
 8      477
 4      276
 5      133
Name: intent, dtype: int64

In [12]:
data['text']=data['text'].str.lower()
data['text'].tail()

127448    @jason my company universe is solving this, an...
127449            @bosotokyo many will get rekt in this nft
127450    @leeneedham81 @kibainuworld @hodl_official @ko...
127451               @1kz3ro @unleashed_nft i love this job
127452    @shill_ronin @unleashed_nft my proof https://t...
Name: text, dtype: object

In [13]:
stopwordlist = ['a', 'about', 'above', 'after', 'again', 'ain', 'all', 'am', 'an',
             'and','any','are', 'as', 'at', 'be', 'because', 'been', 'before',
             'being', 'below', 'between','both', 'by', 'can', 'd', 'did', 'do',
             'does', 'doing', 'down', 'during', 'each','few', 'for', 'from',
             'further', 'had', 'has', 'have', 'having', 'he', 'her', 'here',
             'hers', 'herself', 'him', 'himself', 'his', 'how', 'i', 'if', 'in',
             'into','is', 'it', 'its', 'itself', 'just', 'll', 'm', 'ma',
             'me', 'more', 'most','my', 'myself', 'now', 'o', 'of', 'on', 'once',
             'only', 'or', 'other', 'our', 'ours','ourselves', 'out', 'own', 're','s', 'same', 'she', "shes", 'should', "shouldve",'so', 'some', 'such',
             't', 'than', 'that', "thatll", 'the', 'their', 'theirs', 'them',
             'themselves', 'then', 'there', 'these', 'they', 'this', 'those',
             'through', 'to', 'too','under', 'until', 'up', 've', 'very', 'was',
             'we', 'were', 'what', 'when', 'where','which','while', 'who', 'whom',
             'why', 'will', 'with', 'won', 'y', 'you', "youd","youll", "youre",
             "youve", 'your', 'yours', 'yourself', 'yourselves']

In [14]:
STOPWORDS = set(stopwordlist)
def cleaning_stopwords(text):
    return " ".join([word for word in str(text).split() if word not in STOPWORDS])
data['text'] = data['text'].apply(lambda text: cleaning_stopwords(text))
data['text'].head()

0    @crypto_brody @ecology1990 @moonrunnersnft @it...
1    need sick character art❓#art #artist #artist...
2    @the_hulk_nft @inagotchinft @tesla @killabears...
3    @cryptobatznft @darekbtw first project crypto ...
4    @sashadysonn first project crypto move earn #a...
Name: text, dtype: object

In [15]:
import string
english_punctuations = string.punctuation
punctuations_list = english_punctuations
def cleaning_punctuations(text):
    translator = str.maketrans('', '', punctuations_list)
    return text.translate(translator)
data['text']= data['text'].apply(lambda x: cleaning_punctuations(x))
data['text'].head()

0    cryptobrody ecology1990 moonrunnersnft itsukin...
1    need sick character art❓art artist artists a...
2    thehulknft inagotchinft tesla killabearsnft el...
3    cryptobatznft darekbtw first project crypto mo...
4    sashadysonn first project crypto move earn ast...
Name: text, dtype: object

In [16]:
import re

In [17]:
def cleaning_repeating_char(text):
    return re.sub(r'(.)1+', r'1', text)
data['text'] = data['text'].apply(lambda x: cleaning_repeating_char(x))
data['text'].head()

0    cryptobrody ecolog1990 moonrunnersnft itsukinf...
1    need sick character art❓art artist artists a...
2    thehulknft inagotchinft tesla killabearsnft el...
3    cryptobatznft darekbtw first project crypto mo...
4    sashadysonn first project crypto move earn ast...
Name: text, dtype: object

In [18]:
def cleaning_URLs(text):
    return re.sub('((www.[^s]+)|(https?://[^s]+))',' ',text)
data['text'] = data['text'].apply(lambda x: cleaning_URLs(x))
data['text'].tail()

127448    jason company universe solving this weve got c...
127449                          bosotokyo many get rekt nft
127450    leeneedham1 kibainuworld hodlofficial koacomba...
127451                         1kz3ro unleashednft love job
127452     shillronin unleashednft proof httpstco44di9p2gz7
Name: text, dtype: object

In [19]:
def cleaning_numbers(data):
    return re.sub('[0-9]+', '', data)
data['text'] = data['text'].apply(lambda x: cleaning_numbers(x))
data['text'].tail()

127448    jason company universe solving this weve got c...
127449                          bosotokyo many get rekt nft
127450    leeneedham kibainuworld hodlofficial koacombat...
127451                           kzro unleashednft love job
127452          shillronin unleashednft proof httpstcodipgz
Name: text, dtype: object

In [20]:
from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+|$[0-9]+|\S+')
data['text'] = data['text'].apply(tokenizer.tokenize)
data['text'].head()

0    [cryptobrody, ecolog, moonrunnersnft, itsukinf...
1    [need, sick, character, artâ, “art, artist, a...
2    [thehulknft, inagotchinft, tesla, killabearsnf...
3    [cryptobatznft, darekbtw, first, project, cryp...
4    [sashadysonn, first, project, crypto, move, ea...
Name: text, dtype: object

In [21]:
import nltk
st = nltk.PorterStemmer()
def stemming_on_text(data):
    text = [st.stem(word) for word in data]
    return data
data['text']= data['text'].apply(lambda x: stemming_on_text(x))
data['text'].head()

0    [cryptobrody, ecolog, moonrunnersnft, itsukinf...
1    [need, sick, character, artâ, “art, artist, a...
2    [thehulknft, inagotchinft, tesla, killabearsnf...
3    [cryptobatznft, darekbtw, first, project, cryp...
4    [sashadysonn, first, project, crypto, move, ea...
Name: text, dtype: object

In [22]:
data.head()

id                                               text  \
0  1212762  [cryptobrody, ecolog, moonrunnersnft, itsukinf...   
1  1212763  [need, sick, character, artâ, “art, artist, a...   
2  1212765  [thehulknft, inagotchinft, tesla, killabearsnf...   
3  1212766  [cryptobatznft, darekbtw, first, project, cryp...   
4  1212767  [sashadysonn, first, project, crypto, move, ea...   

                   datetime  intent  
0  2022-08-06T16:56:36.000Z       1  
1  2022-08-06T16:56:36.000Z       3  
2  2022-08-06T16:56:35.000Z       0  
3  2022-08-06T16:56:35.000Z       1  
4  2022-08-06T16:56:34.000Z       1

In [106]:
testdf = data[data['intent'] == -1]
traindf = data[data['intent'] != -1]

In [25]:
traindf 

id                                               text  \
0      1212762  [cryptobrody, ecolog, moonrunnersnft, itsukinf...   
1      1212763  [need, sick, character, artâ, “art, artist, a...   
2      1212765  [thehulknft, inagotchinft, tesla, killabearsnf...   
3      1212766  [cryptobatznft, darekbtw, first, project, cryp...   
4      1212767  [sashadysonn, first, project, crypto, move, ea...   
...        ...                                                ...   
96359  1424490  [nftcryptogang, liuyan, xfedaeeeaadaecbfc, tha...   
96360  1424491  [registered, win, cryptopunksnfts, blokpax, le...   
96361  1424494  [solsniffer, dyor, nft, collection, dictators,...   
96362  1424497  [nft, nftcommmunity, deltaflare, join, discord...   
96363  1424498  [duckbathing, diozoth, elonmusk, richerd, john...   

                       datetime  intent  
0      2022-08-06T16:56:36.000Z       1  
1      2022-08-06T16:56:36.000Z       3  
2      2022-08-06T16:56:35.000Z       0  
3      2022-08-06T16:56:35.000Z       1  
4      2022-08-06T16:56:34.000Z       1  
...                         ...     ...  
96359  2022-08-11T23:11:58.000Z       0  
96360  2022-08-11T23:11:58.000Z       6  
96361  2022-08-11T23:11:58.000Z       0  
96362  2022-08-11T23:11:56.000Z       1  
96363  2022-08-11T23:11:56.000Z       0  

[96364 rows x 4 columns]

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

C:\Users\PRSANYA\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


No. of feature_words:  500000


['aa',
 'aa aa',
 'aa actor',
 'aa big',
 'aa giveaway',
 'aa jbas',
 'aa nft',
 'aa ruggers',
 'aa soon',
 'aa tell',
 'aa thankyouu',
 'aaa',
 'aaa game',
 'aaa games',
 'aaa kind',
 'aaa metahuahua',
 'aaa truly',
 'aaa validator',
 'aaaa',
 'aaaa feature',
 'aaaa milyhossain',
 'aaaaa',
 'aaaaa thank',
 'aaaaaaa',
 'aaaaaaa ðÿ',
 'aaaaaaartz',
 'aaaaaaartz theforgearena',
 'aaaaaaayyyyyyeeeeeyepepe',
 'aaaaaaayyyyyyeeeeeyepepe ðÿš',
 'aaaaaall',
 'aaaaaall good',
 'aaaaaðÿ',
 'aaaaaðÿ x8dðÿ',
 'aaaajb',
 'aaaajb airdropexp',
 'aaaannnndddd',
 'aaaannnndddd offer',
 'aaad',
 'aaad ayyub',
 'aaaeeb',
 'aaaeeb richquack',
 'aaametahuahua',
 'aaametahuahua end',
 'aaannddd',
 'aaannddd another',
 'aaapa',
 'aaapa similar',
 'aaawwam',
 'aaawwam discord',
 'aaayusisilia',
 'aaayusisilia first',
 'aabc',
 'aabidafridi',
 'aabidafridi crypto',
 'aac',
 'aac aac',
 'aac aacpass',
 'aacpass',
 'aacpass nftspace',
 'aacryptoma',
 'aacryptoma enthusiasmnft',
 'aadbtitlic',
 'aadbtitlic featur

In [115]:
traindf = data[data['intent'] != -1]

In [116]:
X=traindf["text"]

In [117]:
Y=traindf["intent"]

In [118]:
from sklearn.model_selection import train_test_split

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X,Y,test_size = 0.05, random_state =26105111)

In [122]:
X_t=X_train.astype(str)

In [123]:
X_s=X_test.astype(str)

In [ ]:
vectoriser = TfidfVectorizer(ngram_range=(1,2), max_features=500000)
vectoriser.fit(X_t)
print('No. of feature_words: ', len(vectoriser.get_feature_names()))

In [ ]:
vectoriser.get_feature_names()

In [124]:
X_train = vectoriser.transform(X_t)
X_test  = vectoriser.transform(X_s)

In [125]:
LRmodel = LogisticRegression(C = 2, max_iter = 1000, n_jobs=-1)
LRmodel.fit(X_train, y_train)

LogisticRegression(C=2, max_iter=1000, n_jobs=-1)

In [126]:
y_pred3 = LRmodel.predict(X_test)

In [127]:
accuracy_score(y_test, y_pred3)

0.9667980908902262

In [128]:
confusion_matrix(y_test, y_pred3)

array([[ 818,    4,    0,    6,    0,    0,    0,    1,    0],
       [  10, 1987,    0,    2,    0,    0,    0,    1,    0],
       [   6,    2,  142,    1,    0,    0,    0,    1,    0],
       [  19,   22,    0, 1049,    0,    0,    0,    2,    0],
       [   5,    3,    0,    1,    9,    0,    0,    0,    0],
       [   0,    0,    0,    0,    0,    9,    0,    0,    0],
       [   2,    4,    0,    2,    0,    0,  261,    2,    0],
       [  21,   33,    0,    7,    0,    0,    1,  369,    1],
       [   0,    1,    0,    0,    0,    0,    0,    0,   15]],
      dtype=int64)

In [153]:
print(classification_report(y_test, y_pred3))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96       829
           1       0.97      0.99      0.98      2000
           2       1.00      0.93      0.97       152
           3       0.98      0.96      0.97      1092
           4       1.00      0.50      0.67        18
           5       1.00      1.00      1.00         9
           6       1.00      0.96      0.98       271
           7       0.98      0.85      0.91       432
           8       0.94      0.94      0.94        16

    accuracy                           0.97      4819
   macro avg       0.98      0.90      0.93      4819
weighted avg       0.97      0.97      0.97      4819



In [129]:
from sklearn.naive_bayes import BernoulliNB

In [130]:
BNBmodel = BernoulliNB()

In [131]:
BNBmodel.fit(X_train, y_train)

BernoulliNB()

In [132]:

y_pred1 = BNBmodel.predict(X_test)
y_pred1 

array([0, 3, 1, ..., 1, 1, 1], dtype=int8)

In [133]:
accuracy_score(y_test, y_pred1)

0.8410458601369579

In [134]:
confusion_matrix(y_test, y_pred1)

array([[ 734,   81,    0,   14,    0,    0,    0,    0,    0],
       [  49, 1893,    0,   56,    0,    0,    0,    2,    0],
       [  74,   75,    3,    0,    0,    0,    0,    0,    0],
       [  47,   29,    0, 1016,    0,    0,    0,    0,    0],
       [   8,    7,    0,    3,    0,    0,    0,    0,    0],
       [   1,    0,    0,    7,    0,    0,    0,    1,    0],
       [   9,  118,    0,   15,    0,    0,  129,    0,    0],
       [  45,   62,    0,   47,    0,    0,    0,  278,    0],
       [   1,    0,    0,    6,    0,    0,    1,    8,    0]],
      dtype=int64)

In [152]:
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.76      0.89      0.82       829
           1       0.84      0.95      0.89      2000
           2       1.00      0.02      0.04       152
           3       0.87      0.93      0.90      1092
           4       0.00      0.00      0.00        18
           5       0.00      0.00      0.00         9
           6       0.99      0.48      0.64       271
           7       0.96      0.64      0.77       432
           8       0.00      0.00      0.00        16

    accuracy                           0.84      4819
   macro avg       0.60      0.43      0.45      4819
weighted avg       0.85      0.84      0.82      4819



C:\Users\PRSANYA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PRSANYA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\PRSANYA\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [136]:
from sklearn.svm import LinearSVC

In [137]:
SVCmodel = LinearSVC()


In [138]:
SVCmodel.fit(X_train, y_train)


LinearSVC()

In [139]:

y_pred2 = SVCmodel.predict(X_test)

In [140]:
accuracy_score(y_test, y_pred2)

0.9769661755550945

In [141]:
y_pred2

array([2, 0, 1, ..., 1, 1, 1], dtype=int8)

In [150]:
from sklearn.metrics import confusion_matrix, classification_report,accuracy_score

In [151]:
print(classification_report(y_test, y_pred2))

              precision    recall  f1-score   support

           0       0.94      0.99      0.96       829
           1       0.98      1.00      0.99      2000
           2       1.00      0.97      0.99       152
           3       0.99      0.97      0.98      1092
           4       0.94      0.89      0.91        18
           5       1.00      1.00      1.00         9
           6       0.99      0.99      0.99       271
           7       0.99      0.88      0.93       432
           8       0.94      1.00      0.97        16

    accuracy                           0.98      4819
   macro avg       0.97      0.96      0.97      4819
weighted avg       0.98      0.98      0.98      4819



In [146]:
X_n=testdf["text"].astype(str)

In [147]:
X_new = vectoriser.transform(X_n)


In [148]:
y_new = SVCmodel.predict(X_new)

In [149]:
y_new

array([7, 3, 7, ..., 7, 0, 2], dtype=int8)